# Generated by Django 4.2.6 on 2023-10-31 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='ball_of_cate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unga quyilgan ball'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='main_categories_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maincategories', verbose_name='Asosiy Kategotiya nomi va idsi'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='is_activte',
            field=models.BooleanField(default=False, verbose_name='Tegilmasin'),
        ),
        migrations.AlterField(
            model_name='maincategories',
            name='ball_of_cate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unga quyiladigan ball'),
        ),
        migrations.AlterField(
            model_name='maincategories',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Asosiy kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='add_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Tegilmasin'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='put_ball',
            field=models.ManyToManyField(related_name='ball_user', to=settings.AUTH_USER_MODEL, verbose_name='Baholovchilar'),
        ),
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='file', verbose_name='Yuborilgan faylar')),
                ('ball', models.IntegerField(blank=True, default=0, null=True, verbose_name='Балл')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Avtor')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fileupload', verbose_name='Savol IDsi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Qaytarilgan ballar',
                'verbose_name_plural': '6 Qaytarilgan ballar',
            },
        ),
    ]
