# Generated by Django 4.2.6 on 2023-10-31 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_categories_ball_of_cate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='repition_ball',
            field=models.ManyToManyField(blank=True, null=True, related_name='repition', to=settings.AUTH_USER_MODEL),
        ),
    ]
