# Generated by Django 4.2.6 on 2023-10-31 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fileupload_repition_ball'),
    ]

    operations = [
        migrations.RenameField(
            model_name='putball',
            old_name='ball',
            new_name='files_get',
        ),
    ]
